/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhanxiang_simplegridview_utils_MusicPlay */

#ifndef _Included_com_xiaozhanxiang_simplegridview_utils_MusicPlay
#define _Included_com_xiaozhanxiang_simplegridview_utils_MusicPlay
#ifdef __cplusplus
extern "C" {
#endif

#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libavfilter/avfilter.h"
#include <libswresample/swresample.h>
#include "android_debug.h"
//像素处理
#include "libswscale/swscale.h"
/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_MusicPlay
 * Method:    playSound
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiaozhanxiang_simplegridview_utils_MusicPlay_playSound
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_xiaozhanxiang_simplegridview_utils_MusicPlay_testWhile
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
