/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaozhanxiang_simplegridview_utils_JNIUtils */

#ifndef _Included_com_xiaozhanxiang_simplegridview_utils_JNIUtils
#define _Included_com_xiaozhanxiang_simplegridview_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    getNativeValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_getNativeValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    nativeInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_nativeInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    nativeArrayJava
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_nativeArrayJava
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    callJavaVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_callJavaVoid
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    callJavaString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_callJavaString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaozhanxiang_simplegridview_utils_JNIUtils
 * Method:    callJavaArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_xiaozhanxiang_simplegridview_utils_JNIUtils_callJavaArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
